name: 05 - 01 Event Filters and Activity Types

on: 
    pull_request:
        types:
        - opened
        - synchronize
        branches:
        - main
jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            -   name: Echo Event Type
                run: echo "runs when a PR is raised