name: 05 - 02 - Event Filters and Activity Types

on: 
    pull_request:
        types:
        - closed
        branches:
        - main
jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            -   name: Echo Event Type
                run: echo "Runs when a PR is closed"