name: 09 - Using Functions
on:
    pull_request:
    workflow_dispatch:
jobs:
    echo1:
        runs-on: ubuntu-latest
        steps:
        - name: Print PR title
          run: echo "${{github.event.pull_request.title}}"
        - name: Print PR labels
          run: |
              cat << EOF
              $ {{toJSON(github.event.pull_request.labels}}
              EOF
        - name: Bug step
          if: ${{ !cancelled() && contains(github.event.pull_request.title,'fix')}}
          run: echo "I am a bug fix"
        - name: Sleep for 20 seconds
          run: sleep 20
        - name: Failing step
          run: exit 1
        - name: This step will be skipped
          if: ${{ success() }}
          run: echo "This step will be skipped"
        - name: This step will be skipped too
          if: ${{ failure() }}
          run: echo "This step will be run if any previous step fails"
        - name: This step will run
          if: ${{ always() }}
          run: echo "This step will run"
        - name: This step will be skipped
          if: ${{ cancelled() }}
          run: echo "This step will run if the previous workflow is cancelled."

